### PR TITLE
Day 25 in python

### PR DESCRIPTION
**Pull request by ChetasShree**
Solved this question "To merge 2 arrays into a third array" using python.

### CODE REVIEW

**Review by vanshita2123 — CHANGES_REQUESTED** [review]
Your code isn't generating desired O/P.
Try again.
WhatsApp Image 2021-03-27 at 12 04 41 AM

**Comment by ChetasShree** [comment]
@vanshita2123, the two arrays got merged and at the same time got sorted. So the array shouldn't get sort ?? only merge the two arrays without sorting??

**Comment by ChetasShree** [comment]
@vanshita2123  please check the code now, I made the changes. Thank you.

**Comment by shubhigupta991** [comment]
Its still not working properly for day 25

**Comment by shubhigupta991** [comment]
Also for Day 26 it was clearly mentioned that you should create function. The correction in Day 22 code was fine but now you need to create a separate PR for that.  So closing this PR.

**Pull request closed without merging**
