### PR TITLE
Code Day 25

### PR DESCRIPTION
**Pull request by Fab-Gaurav**

### CODE REVIEW

**Review by vanshita2123 — CHANGES_REQUESTED** [review]
Your code isn't generating the desired output.
Try again.
image (4)

**Comment by Fab-Gaurav** [comment]
@vanshita2123 
Have a look : https://github.com/CodeTrophs/MarchCode/pull/311/commits/0f5ab85bc16f0bcc0530b94accfe71949e573d31
Issue #311 
I made desired changes to the code.

**Comment by shubhigupta991** [comment]
It is still not giving the desired o/p. So closing this PR.

**Comment by Fab-Gaurav** [comment]
> It is still not giving the desired o/p. So closing this PR.

Their's not's an issue of closing the PR but will you please tell me how the updated code is also wrong??

**Pull request closed without merging**
