### PR TITLE
Day 1 contribution

### PR DESCRIPTION
**Pull request by kritikashah20**

### CODE REVIEW

**Comment by shubhigupta991** [comment]
Late contribution

**Comment by kritikashah20** [comment]
My Day 6 Contribution also won't be counted?

**Comment by shubhigupta991** [comment]
No you need to create separate PR according to rules.

**Comment by kritikashah20** [comment]
Okay..Thank you

**Comment by kritikashah20** [comment]
I have created PR for Day 6 #110  Please review it.

**Pull request closed without merging**
